<!--
Source: nucleo-ui-outline-18@1.5.1 (npm), dist/components/IconLoaderOutline18.js
Original name: IconLoaderOutline18
https://www.npmjs.com/package/nucleo-ui-outline-18/v/1.5.1
-->
<script lang="ts">
	import IconRoot from './IconRoot.svelte';
	import type { IconProps } from './types';

	let { strokeWidth = 1.5, ...props }: IconProps = $props();
</script>

<IconRoot {...props}>
	<line
		x1="9"
		y1="1.75"
		x2="9"
		y2="4.25"
		fill="none"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
	<line
		x1="14.127"
		y1="3.873"
		x2="12.359"
		y2="5.641"
		fill="none"
		opacity=".88"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
	<line
		x1="16.25"
		y1="9"
		x2="13.75"
		y2="9"
		fill="none"
		opacity=".75"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
	<line
		x1="14.127"
		y1="14.127"
		x2="12.359"
		y2="12.359"
		fill="none"
		opacity=".63"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
	<line
		x1="9"
		y1="16.25"
		x2="9"
		y2="13.75"
		fill="none"
		opacity=".5"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
	<line
		x1="3.873"
		y1="14.127"
		x2="5.641"
		y2="12.359"
		fill="none"
		opacity=".38"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
	<line
		x1="1.75"
		y1="9"
		x2="4.25"
		y2="9"
		fill="none"
		opacity=".25"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
	<line
		x1="3.873"
		y1="3.873"
		x2="5.641"
		y2="5.641"
		fill="none"
		opacity=".13"
		stroke="currentColor"
		stroke-linecap="round"
		stroke-linejoin="round"
		stroke-width={strokeWidth}
	/>
</IconRoot>
